name: CI
on:
  push:
    branches:
      - main
      - release/**
      - feature/**
      - fix/**
  pull_request:
    branches:
      - main
      - release/**

jobs:
  lint-test:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (flake8/black/isort)
        run: |
          flake8 .
          black --check .
          isort --check-only .

      - name: Schema smoke
        run: |
          python -c "import importlib, sys; importlib.import_module('system_audit'); print('schema smoke ok')"
